name: Deploy Challenges

on:
  push:
    branches: ["dev"]

# manual trigger or event triggers a workflow: runs 1(+) jobs, which executes on a runner machine and runs series of 1(+) steps
# steps can run a script you define or run an action (reusable action)
# each step runs in its own process (so env variables not preserved between steps)
# workflows defined in `.github/workflows`
jobs:
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        challenge: ["chall1", "chall2", "chall3"]
    steps:
      - name: Test Matrix
        run: |
          echo ${{ matrix.challenge }}
