name: Deploy Challenges

on:
  push:
    branches: ["dev"]

# manual trigger or event triggers a workflow: runs 1(+) jobs, which executes on a runner machine and runs series of 1(+) steps
# steps can run a script you define or run an action (reusable action)
# each step runs in its own process (so env variables not preserved between steps)
# workflows defined in `.github/workflows`

jobs:
  GET-ALL-CHALLENGES:
    runs-on: ubuntu-latest
    outputs:
      challenges: ${{ steps.get-challenges.outputs.challenges }}
    steps:
      - uses: actions/checkout@v4
      # TODO: add comments for this
      - name: Get Challenges
        id: get-challenges
        run: |
          # Find all challenge dirs two levels deep: /challenges/<category>/<challenge>
          json=$(find challenges -mindepth 2 -maxdepth 2 -type d -printf '%P\n' \
            | jq -R . | jq -c -s .)
          echo "challenges=$json" >> "$GITHUB_OUTPUT"
  # TODO: add a job here that stops execution if no files where changed
  # TODO: these respectively should only trigger for challenges with `/static/` or have docker-compose
  per-challenge:
    name: ${{ matrix.challenge }}
    needs: GET-ALL-CHALLENGES
    runs-on: ubuntu-latest
    strategy:
      matrix:
        challenge: ${{ fromJson(needs.define-challenges-matrix.outputs.challenges) }}
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate With GCP (for deploy)
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          version: ">= 363.0.0"
      - name: Upload Static Files (If Present)
        if: steps.check_static.outputs.files_exists == 'true'
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: "challenges/${{ matrix.challenge }}/static"
          headers: |-
            content-disposition: 'attachment'
          destination: "${{ vars.STATIC_ASSETS_BUCKET_NAME }}/${{ matrix.challenge }}"
      - name: "Use gcloud CLI"
        run: "gcloud compute instances list"
      # - name: Create CTFd Challenge Entry or Update CTFd Challenge Entry Connection Info
