name: Deploy Challenges

on:
  push:
    branches: ["dev"]

# manual trigger or event triggers a workflow: runs 1(+) jobs, which executes on a runner machine and runs series of 1(+) steps
# steps can run a script you define or run an action (reusable action)
# each step runs in its own process (so env variables not preserved between steps)
# workflows defined in `.github/workflows`
jobs:
  define_challenges_matrix:
    runs-on: ubuntu-latest
    outputs:
      challenges: ${{ steps.get_challenges.outputs.challenges }}
    steps:
      - name: Get Challenges
        id: get_challenges
        run: |
          # Find all challenge dirs two levels deep: /challenges/<category>/<challenge>
          challenges=$(find challenges -mindepth 2 -maxdepth 2 -type d | sed 's|challenges/||' | tr '/' '-')

          # Convert to JSON array
          json=$(printf '%s\n' $challenges | jq -R . | jq -s .)

          echo "challenges=$json" >> $GITHUB_OUTPUT
