name: Deploy Challenges

on:
  push:
    branches: ["dev"]

jobs:
  get-all-challenges:
    runs-on: ubuntu-latest
    outputs:
      # `challenges` will be a list of challenges formatted as "<category>/<challenge-name>" (ex. ["osint/geoguesser","web/xss","crypto/xor","rev/crackme","misc/pyjail","hardware/pcb","forensics/file-analysis","pwn/shellcode"])
      challenges: ${{ steps.get-challenges.outputs.challenges }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Challenges
        id: get-challenges
        run: |
          # Find all challenge dirs two levels deep: /challenges/<category>/<challenge>
          json=$(find challenges -mindepth 2 -maxdepth 2 -type d -printf '%P\n' \
            | jq -R . | jq -c -s .)
          echo "challenges=$json" >> "$GITHUB_OUTPUT"
  update-gcp:
    runs-on: ubuntu-latest
    needs: get-all-challenges
    env:
      CHALLENGES: ${{ needs.get-all-challenges.outputs.challenges }}
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate With GCP
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          version: ">= 363.0.0"
          project_id: ${{ vars.GCP_PROJECT_ID }}
      - name: Copy latest files onto VM
        id: collect
        run: |
          # TODO: have to manually install docker on the VM rn - add as a step 
          gcloud compute ssh cyber_f25_0000@challenges --zone=us-east1-b --command="[ -d /home/cyber_f25_0000/challenges ] && rm -rf /home/cyber_f25_0000/challenges"
          # [ -d <path> ] is used to check if the directory exists, and remove if so
          gcloud compute scp --zone=us-east1-b --recurse challenges cyber_f25_0000@challenges:/home/cyber_f25_0000

          results='{}'

          for challenge in $(jq -r '.[]' <<<"$CHALLENGES"); do # loop through the challenges array 
            echo "Challenge $challenge"
            
            # TODO: verify that this will exit as 0 if the compose.yaml simply does not exist 
            gcloud compute ssh cyber_f25_0000@challenges --zone=us-east1-b --command="[ -f /home/cyber_f25_0000/challenges/$challenge/compose.yaml ] && sudo docker compose -f /home/cyber_f25_0000/challenges/$challenge/compose.yaml up -d --build || echo 'No compose.yaml found, skipping.'" &> challenge.log
            
          # TODO: update archive file for it (need to parse the path? or can create in "challenge" path?) 
            rc=$? # get exit code 
            results=$(jq --arg c "$challenge" --argjson rc "$rc" '. + {($c):$rc}' <<<"$results")
          done 
          echo "matrix=$(jq -c 'to_entries | map({challenge:.key, code:.value})' <<<"$results")" >> "$GITHUB_OUTPUT"
  post-step:
    - name: Run per-challenge post-step
      needs: update-gcp
      runs-on: ubuntu-latest
      strategy:
        matrix:
          include: ${{ fromJson(needs.update-gcp.outputs.matrix) }}
      steps:
        - name: Print info
          run: |
            echo "Challenge: ${{ matrix.challenge }}"
            echo "Exit code: ${{ matrix.code }}"
