name: Deploy Challenges Draft

on:
  push:
    branches: ["dev"]

# manual trigger or event triggers a workflow: runs 1(+) jobs, which executes on a runner machine and runs series of 1(+) steps
#      - note that all the steps in a job execute on the same runner machine (so they will share the same filesystem)
#         - each step runs in its own shell, so exported variables only persist within a single step unless explicitly saved using the "set-output" or $GITHUB_ENV mechanism
# steps can run a script you define or run an action (reusable action)
# each step runs in its own process (so env variables are NOT preserved between steps)
# workflows defined in .github/workflows

jobs:
  # TODO: split up the job so copying work is done on a nother step ?
  GET-ALL-CHALLENGES:
    runs-on: ubuntu-latest
    outputs:
      challenges: ${{ steps.get-challenges.outputs.challenges }}
    steps:
      - uses: actions/checkout@v4
      # TODO: add comments for this
      - name: Get Challenges
        id: get-challenges
        run: |
          # Find all challenge dirs two levels deep: /challenges/<category>/<challenge>
          json=$(find challenges -mindepth 2 -maxdepth 2 -type d -printf '%P\n' \
            | jq -R . | jq -c -s .)
          echo "challenges=$json" >> "$GITHUB_OUTPUT"
      - name: Authenticate With GCP (for deploy)
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          version: ">= 363.0.0"
          project_id: ${{ vars.GCP_PROJECT_ID }}
      # - name: Copy latest files onto VM(s)
      #   # this logic makes it so that you don't need to create the `challenges` directory on the VM, however you WILL have to install Docker
      #   run: |
      #     gcloud compute ssh cyber_f25_0000@challenges --zone=us-east1-b --command="[ -d /home/cyber_f25_0000/challenges ] && rm -rf /home/cyber_f25_0000/challenges"
      #     # [ -d <path> ] is used to check if the directory exists, and remove if so
      #     gcloud compute scp --zone=us-east1-b --recurse challenges cyber_f25_0000@challenges:/home/cyber_f25_0000
      #   # then in the next command just make it do "docker compose up -d --build"

  # TODO: add a job here that stops execution if no files where changed
  # TODO: should I make some executions only trigger for challenges with /static/ or have docker-compose

  set-up-GCP-VMs:
    runs-on: ubuntu-latest
    needs: GET-ALL-CHALLENGES
    # docker compose up -d --build &> challenge-logs/<challenge-name>.log
    # exit_code=$?
    # this command will overwrite the contents of the log file, do you need to make it? also need to make challenge-logs directory?
    # this command will return 1 if it failed
    # output a matrix that is path to exit codes, depending on exit codes fail or not fail

    # should only run this if the challenge folder has a compose.yaml
    # gcloud compute ssh cyber_f25_0000@challenges --zone=us-east1-b --command="sudo docker compose -f /home/cyber_f25_0000/challenges/crypto/xor/compose.yaml up -d --build" &> challenge.log
    # challenge.log will be on the runner machine
    # the exit code will come from gcloud compute ssh, which is propogated from the remote command's exit code back to the local shell
    # so $? on local machine will give you exit code of the remote command, unless the SSH connection itself failed (in which gcloud exists with 255)

  # dynamic challenges: crypto/xor, misc/pyjail, pwn/shellcode, web/xss
  per-challenge-deploy-on-gcp:
    name: ${{ matrix.challenge }}
    needs: GET-ALL-CHALLENGES
    runs-on: ubuntu-latest
    # env:
    strategy:
      matrix:
        challenge: ${{ fromJson(needs.GET-ALL-CHALLENGES.outputs.challenges) }}
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate With GCP (for deploy)
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          version: ">= 363.0.0"
          project_id: ${{ vars.GCP_PROJECT_ID }}
      - name: "Run each dynamic challenge"
        run: |
          # gcloud compute ssh cyber_f25_0000@challenges --zone=us-east1-b --command="sudo docker compose -f /home/cyber_f25_0000/challenges/${{ matrix.challenge }} up -d --build"
           gcloud compute ssh cyber_f25_0000@challenges --zone=us-east1-b --command="ls"

  #
  per-challenge-deploy-to-ctfd:
    name: ${{ matrix.challenge }}
    needs: GET-ALL-CHALLENGES
    runs-on: ubuntu-latest
    env:
      CTFD_TOKEN: ${{ secrets.CTFD_TOKEN }}
      CTFD_DOMAIN: ${{ vars.CTFD_DOMAIN }}
      CHALLENGE_PATH: ${{ matrix.challenge }}
      EXISTING_CHALLENGES: ${{ vars.EXISTING_CHALLENGES }}
    strategy:
      matrix:
        challenge: ${{ fromJson(needs.GET-ALL-CHALLENGES.outputs.challenges) }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4 # this will place repo in $GITHUB_WORKSPACE
      - name: Set up Python
        uses: actions/setup-python@v5 # is this latest?
      - name: Check if new challenge # reword this
        run: python infra/is_new_challenge.py
      - name: Run script to deploy to CTFd # reword this
        run: python infra/create_challenge.py

        # copy over repo
        # run the create_challenge.py with repo cloned in, path passed in, and CTFD_TOKEN, CTFD_URL, + other stuff? injected as env variables
