name: Deploy Challenges

on:
  push:
    branches: ["dev"]

# manual trigger or event triggers a workflow: runs 1(+) jobs, which executes on a runner machine and runs series of 1(+) steps
#      - note that all the steps in a job execute on the same runner machine (so they will share the same filesystem)
#         - each step runs in its own shell, so exported variables only persist within a single step unless explicitly saved using the "set-output" or $GITHUB_ENV mechanism
# steps can run a script you define or run an action (reusable action)
# each step runs in its own process (so env variables are NOT preserved between steps)
# workflows defined in .github/workflows

jobs:
  GET-ALL-CHALLENGES:
    runs-on: ubuntu-latest
    outputs:
      challenges: ${{ steps.get-challenges.outputs.challenges }}
    steps:
      - uses: actions/checkout@v4
      # TODO: add comments for this
      - name: Get Challenges
        id: get-challenges
        run: |
          # Find all challenge dirs two levels deep: /challenges/<category>/<challenge>
          json=$(find challenges -mindepth 2 -maxdepth 2 -type d -printf '%P\n' \
            | jq -R . | jq -c -s .)
          echo "challenges=$json" >> "$GITHUB_OUTPUT"
      - name: Authenticate With GCP (for deploy)
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          version: ">= 363.0.0"
          project_id: ${{ vars.GCP_PROJECT_ID }}
      - name: Copy latest files onto VM(s)
        run: |
          gcloud compute ssh cyber_f25_0000@challenges --zone=us-east1-b --command="[ -d /home/cyber_f25_0000/challenges ] && rm -rf /home/cyber_f25_0000/challenges"
          # [ -d <path> ] is used to check if the directory exists, and remove if so 
          gcloud compute scp --zone=us-east1-b --recurse challenges cyber_f25_0000@challenges:/home/cyber_f25_0000
        # then in the next command just make it do "docker compose up -d --build"

  # TODO: add a job here that stops execution if no files where changed
  # TODO: should I make some executions only trigger for challenges with /static/ or have docker-compose

  per-challenge-deploy-on-gcp:
    name: ${{ matrix.challenge }}
    needs: GET-ALL-CHALLENGES
    runs-on: ubuntu-latest
    # env:
    strategy:
      matrix:
        challenge: ${{ fromJson(needs.GET-ALL-CHALLENGES.outputs.challenges) }}
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate With GCP (for deploy)
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          version: ">= 363.0.0"
          project_id: ${{ vars.GCP_PROJECT_ID }}
  #       - name: Upload Static Files (If Present)
  #         if: ${{ hashFiles(format('challenges/{0}/static/**', matrix.challenge)) != '' }}
  #         uses: google-github-actions/upload-cloud-storage@v2
  #         with:
  #           path: "challenges/${{ matrix.challenge }}/static"
  #           parent: false
  #           headers: |-
  #             content-disposition: 'attachment'
  #           destination: "${{ vars.STATIC_ASSETS_BUCKET_NAME }}/${{ matrix.challenge }}"
  #       - name: Setup SSH key
  #         run: |
  #           mkdir -p ~/.ssh
  #           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/git2ctf
  #           chmod 600 ~/.ssh/git2ctf
  #           echo "Host *\n  StrictHostKeyChecking no\n  IdentityFile ~/.ssh/git2ctf" >> ~/.ssh/config
  #       - name: Copy challenge dir
  #         run: |
  #           scp -r challenges/${{ matrix.challenge }} \
  #             ${{ vars.VM_USER }}@${{ vars.VM_NAME }}:/home/${{ vars.VM_USER }}/challenges/
  #       - name: Deploy
  #         run: |
  #           ssh ${{ vars.VM_USER }}@${{ vars.VM_NAME }} \
  #             "cd /home/${{ vars.VM_USER }}/challenges/${{ matrix.challenge }} && sudo docker compose up --build -d"
  #
  per-challenge-deploy-to-ctfd:
    name: ${{ matrix.challenge }}
    needs: GET-ALL-CHALLENGES
    runs-on: ubuntu-latest
    env:
      CTFD_TOKEN: ${{ secrets.CTFD_TOKEN }}
      CTFD_DOMAIN: ${{ vars.CTFD_DOMAIN }}
      CHALLENGE_PATH: ${{ matrix.challenge }}
      EXISTING_CHALLENGES: ${{ vars.EXISTING_CHALLENGES }}
    strategy:
      matrix:
        challenge: ${{ fromJson(needs.GET-ALL-CHALLENGES.outputs.challenges) }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4 # this will place repo in $GITHUB_WORKSPACE
      - name: Set up Python
        uses: actions/setup-python@v5 # is this latest?
      - name: Check if new challenge # reword this
        run: python infra/is_new_challenge.py
      - name: Run script to deploy to CTFd # reword this
        run: python infra/create_challenge.py

        # copy over repo
        # run the create_challenge.py with repo cloned in, path passed in, and CTFD_TOKEN, CTFD_URL, + other stuff? injected as env variables
