name: PR Checks
on:
  pull_request:
    branches: [dev]

jobs:
  get-challenges:
    runs-on: ubuntu-latest
    name: Get challenges in PR
    permissions:
      pull-requests: read
    outputs:
      challenge-paths: ${{ steps.changed-files.outputs.ALL_CHANGED_FILES }}

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          files: challenges/**

      - name: List all changed files
        id: changed-files
        env:
          # TODO: do we want to strip the "/challenges"?
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
          echo ${ALL_CHANGED_FILES} >> "$GITHUB_OUTPUT"

  run-checks:
    runs-on: ubuntu-latest
    needs: get-challenges
    strategy:
      matrix:
        challenge-path: ${{ fromJSON(needs.get-challenges.outputs.challenge-paths )}}
    steps:
      - name: Print path
        env:
          challenge-path: ${{ matrix.challenge-path }}
        run: |
          echo $challenge-path
