name: PR Checks

on:
  pull_request:
    branches: ["dev"]

jobs:
  get-challenges:
    name: Get challenges in PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      challenge-paths: ${{ steps.collect.outputs.json }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@v47
        with:
          files: challenges/**

      - name: Log all changed files
        run: |
          for f in ${{ steps.changed.outputs.all_changed_files }}; do
            echo "$f was changed"
          done

      - name: Collect challenge paths as JSON
        id: collect
        shell: python
        run: |
          import json
          import os
          import sys
          #TODO: trim out the "challenges/" here?
          # Filter out empty and non-challenge paths if needed - TODO: we don't need this
          changed = os.getenv("ALL_CHANGED_FILES", "").strip().split()
          changed = [c for c in changed if c.startswith("challenges/")]
          changed = sorted(set(changed))
          json_output = json.dumps(changed)
          print(f"json={json_output}")
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              print(f"json={json_output}", file=f)
        env:
          ALL_CHANGED_FILES: ${{ steps.changed.outputs.all_changed_files }}

  run-checks:
    name: Run the checks
    runs-on: ubuntu-latest
    needs: get-challenges
    # Skip if no challenge files changed
    if: ${{ needs.get-challenges.outputs.challenge-paths != '[]' }}
    strategy:
      matrix:
        challenge-path: ${{ fromJSON(needs.get-challenges.outputs.challenge-paths) }}
    steps:
      - name: Print path
        run: echo "${{ matrix.challenge-path }}"
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Install Docker Compose
      #   uses: docker/setup-compose-action@v3
      # - name: Run checks
      #   run: python infra/pr_checks.py unique-port
      #   env:
      #   CHALLENGE_PATH: ${{ matrix.challenge-path }}
